# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-12 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('person', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('company_id', models.IntegerField()),
            ],
            options={
                'db_table': 'bid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('info_url', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('artificial_person', models.CharField(max_length=255)),
                ('registered_capital', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('registered_date', models.DateField(blank=True, null=True)),
                ('industry', models.CharField(max_length=255)),
                ('registered_number', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('organization_number', models.CharField(max_length=255)),
                ('operation_period', models.CharField(max_length=255)),
                ('registered_authority', models.CharField(max_length=255)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('credit_number', models.CharField(max_length=255)),
                ('registered_location', models.CharField(max_length=255)),
                ('business_scope', models.TextField(blank=True, null=True)),
                ('country', models.CharField(max_length=255)),
                ('market_value', models.CharField(max_length=255)),
                ('sales_amount_last_year', models.CharField(max_length=255)),
                ('sales_profit_last_year', models.CharField(max_length=255)),
                ('introduction', models.CharField(max_length=255)),
                ('major_business', models.TextField()),
                ('major_product', models.CharField(max_length=255)),
                ('company_copyright', models.TextField()),
                ('company_copyright_score', models.FloatField()),
                ('company_patent', models.TextField()),
                ('company_patent_score', models.FloatField()),
                ('company_competition', models.TextField()),
                ('company_competition_score', models.FloatField()),
                ('company_conference', models.TextField()),
                ('company_conference_score', models.FloatField()),
                ('company_loophole', models.TextField()),
                ('company_loophole_score', models.FloatField()),
                ('company_honor', models.TextField()),
                ('company_honor_score', models.FloatField()),
                ('company_market_share', models.TextField()),
                ('company_market_share_score', models.FloatField()),
                ('company_new_product', models.TextField()),
                ('company_new_product_score', models.FloatField()),
                ('company_award', models.TextField()),
                ('company_award_score', models.FloatField()),
                ('company_industry_coverage', models.TextField()),
                ('company_ceo', models.CharField(max_length=255)),
                ('company_tech_team', models.TextField()),
                ('company_employees_number', models.CharField(max_length=255)),
                ('company_employees_number_score', models.FloatField()),
                ('company_postgraduate', models.CharField(max_length=255)),
                ('company_undergraduate', models.CharField(max_length=255)),
                ('company_research_percent', models.CharField(max_length=255)),
                ('company_research_percent_score', models.FloatField()),
                ('company_on_market', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Copyright',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('shorthand', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('classification', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('company_id', models.IntegerField()),
            ],
            options={
                'db_table': 'copyright',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('artificial_person', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('company_id', models.IntegerField()),
            ],
            options={
                'db_table': 'investment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('company_id', models.IntegerField()),
            ],
            options={
                'db_table': 'management',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('artificial_person', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('company_id', models.IntegerField()),
            ],
            options={
                'db_table': 'shareholder',
                'managed': False,
            },
        ),
    ]
